apiVersion: v1
kind: Service
metadata:
  name: fe-usermgmt-service
spec:
  selector:
    app: fe-usermgmt
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 3000
  type: LoadBalancer